plugins {
    id 'java'
    id 'idea'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.3'
    id 'hytale-mod' version '0.+'
}

ext {
    hytaleHome = "${System.getProperty("user.home")}/AppData/Roaming/Hytale"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
}

javadoc {
    options.addStringOption('Xdoclint:-missing', '-quiet')
}

def serverJar = file("$hytaleHome/install/$patchline/package/game/latest/Server/HytaleServer.jar")
def serverSrcZip = file("$hytaleHome/install/$patchline/package/game/latest/Server/HytaleServer-src.zip")

 gradle.projectsEvaluated {
     if (serverJar.exists() && (!serverSrcZip.exists() || serverJar.lastModified() > serverSrcZip.lastModified())) {
         gradle.startParameter.taskNames = ['decompileServer'] + gradle.startParameter.taskNames
     }
 }

dependencies {
    implementation files(serverJar)
}


processResources {
    def expandProps = [
            "version"                      : version,
            "mod_id"                       : mod_id,
            "mod_name"                     : mod_name,
            "description"                  : description
    ]

    filesMatching(['manifest.json']) {
        expand expandProps
    }
    inputs.properties(expandProps)
}


def serverRunDir = file("$projectDir/run")
if (!serverRunDir.exists()) {
    serverRunDir.mkdirs()
}

tasks.register('updatePluginManifest') {
    def manifestFile = file('src/main/resources/manifest.json')
    doLast {
        if (!manifestFile.exists()) {
            throw new GradleException("Could not find manifest.json at ${manifestFile.path}!")
        }
        def manifestJson = new groovy.json.JsonSlurper().parseText(manifestFile.text)
        manifestJson.Version = version
        manifestJson.IncludesAssetPack = includes_pack.toBoolean()
        manifestFile.text = groovy.json.JsonOutput.prettyPrint(groovy.json.JsonOutput.toJson(manifestJson))
    }
}

tasks.named('processResources') {
    dependsOn 'updatePluginManifest'
}